### ISSUE TITLE
Roadmap: Cold Importer

### ISSUE THREAD

**Issue by ghost** [hermanjunge/go-ipld-eth-import#1]
### Overview

The Cold importer for each kind of object has two tiers:

* Traverse throughout a disconnected geth levelDB and dump found contents into file system, to be processed afterwards. i.e. It can be compressed, shared, divided, etc.
* Import from file directory into a disconnected IPFS repository.

The idea of having two tiers is that this approach improves the scaling of this process.

### Has

- [x] `eth-evm-code`
  - [x] LevelDB to File System
  - [x] File System to IPFS

#### Ethereum Objects

- [ ] `eth-state-trie`
  - [x] LevelDB to File System
  - [ ] File System to IPFS 
- [ ] `eth-block`
- [ ] `eth-tx-trie` + `eth-tx`
- [ ] `eth-tx-receipt-trie` + `eth-tx-receipt`
- [ ] `eth-storage-trie`
- [ ] `eth-block-list` (a.k.a. Ommers list)

#### Improvements

- [ ] Provide tools to check whether we have a complete state in our local node.

**Comment by ghost** [comment]
[See here](https://github.com/MetaMask/mustekala/issues/2)
